### ISSUE TITLE
startUser not defined

### ISSUE THREAD

**Issue by Rahul-Yadav-1996** [anirudhganwal06/remote-me#2]
both file user and controller have same issue for not defined startUser and startController . 
how to solve this error . plz guide .

**Comment by anirudhganwal06** [comment]
Hi Rahul,
For running the program, just run the main.py file.

If you separately want to run user.py and controller.py, change startUser() to startUserDisplay() or startUserMouseControl() [here](https://github.com/anirudhganwal06/remote-me/blob/4077ea2a39df6b73f48e43e833da32e9dd6eda70/remote-me/user.py#L79) and same applies to controller.py. 
Since, the main program doesn't need the main function of user and controller, I forgot to update the function name there.

Please ask if you need further help.

**Comment by Rahul-Yadav-1996** [comment]
how to stop screen garbing?

**Comment by Rahul-Yadav-1996** [comment]
how to stop screen grabing ?

**Comment by anirudhganwal06** [comment]
By screen grabbing if you mean how to stop screen sharing, that functionality I didn't create at the time.I worked on this project a long time ago.. I guess currently you just have to close the program to stop screen sharing.

**Comment by Rahul-Yadav-1996** [comment]
When I run main file twice in same PC ( first share my screen And other
terminal watch another screen ) then multiple window open one by one . So
how to solve this issue  .

**Comment by anirudhganwal06** [comment]
This shouldn't happen...

**Comment by anirudhganwal06** [comment]
Are you sure there are multiple windows coming up.. it may be because of the screen sharing within the same PC which is shared recursively that gives the illusion of multiple windows.

**Comment by Rahul-Yadav-1996** [comment]
i have a problem  when run main.py in my computer , screen are
continue going inside look like a loop execute . i took a pic of this
iisue. and  can u tell me this project work on other network because at
that time i only use in same network. i am also work on python i have
project on remote desktop . i am also live nearby kosli .
thanks.
